version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
  producer1:
    build:
      context: ./producer1
      dockerfile: Dockerfile
    container_name: producer1
    depends_on:
      - broker
      - zookeeper
    environment:
      - BROKER_ADDRESS1=broker:9092
  
  producer2:
    build:
      context: ./producer2
      dockerfile: Dockerfile
    container_name: producer2
    depends_on:
      - broker
      - zookeeper
    environment:
      - BROKER_ADDRESS2=broker:9093
  

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - broker
      - zookeeper
    environment:
      - BROKER_ADDRESS1=broker:9092
      - BROKER_ADDRESS2=broker:9093
    ports:
      - "9010:9010"   

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"    
